PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX frbroo: <http://iflastandards.info/ns/fr/frbr/frbroo/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?work ?workId ?title ?author ?date WHERE {
  ?work a frbroo:F1_Work ;
    crm:P1_is_identified_by ?idNode ;
    crm:P102_has_title ?titleNode ;
    crm:P94_has_created ?author ;
    crm:P4_has_time-span ?dateSpan ;
    crm:P67_refers_to <http://example.org/site/alpha> .
  
  ?idNode crm:P190_has_symbolic_content ?workId .
  ?titleNode crm:P190_has_symbolic_content ?title .
  ?author crm:P131_is_identified_by ?authorName .
  ?authorName crm:P190_has_symbolic_content ?author .
  ?dateSpan crm:P82_at_some_time_within ?date .
}
ORDER BY ?date
